[package]
name = "vault"
version = "0.1.0"
authors = ["timglabisch <glabisch@easybill.de>"]

[dependencies]
openssl = "0.10.*"
toml = "0.5.*"
serde_derive = "*"
serde = "*"
clap = "3.*"
regex = "1.*"
failure = "0.1.*"
failure_derive = "0.1.*"
byteorder = "1.*"
dirs = "4.*"