[package]
name = "vault"
version = "1.0.10"
authors = ["timglabisch <glabisch@easybill.de>"]

[dependencies]
openssl = {version = "0.10.*", features = ["vendored"]}
toml = "0.5.*"
serde_derive = "*"
serde = "*"
clap = "3.*"
regex = "1.7.*"
anyhow = "1.0.*"
byteorder = "1.4.*"
dirs = "4.0.*"
globset = "0.4.*"
self_update = "0.*"