[package]
name = "vault"
version = "0.1.0"
authors = ["timglabisch <glabisch@easybill.de>"]

[dependencies]
openssl = {version = "0.10.*", features = ["vendored"]}
toml = "0.5.*"
serde_derive = "*"
serde = "*"
clap = "3.*"
regex = "1.*"
anyhow = "1.*"
byteorder = "1.*"
dirs = "4.*"